services:
  nest-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached

    command: sleep infinity
    depends_on:
      - nest-dev-postgres
    network_mode: service:nest-dev-postgres

  nest-dev-postgres:
    image: postgres:15
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-dev-redis:
    env_file:
      - ../.env
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
