services:
  nest-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
     
    command: sleep infinity

  nest-dev-postgres:
    image: postgres:15
    env_file:
      - ../.env
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  nest-dev-redis: 
    env_file:
      - ../.env
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: