services:
  nest-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached

    ports:
      - "3000:3000"
      
    command: sleep infinity


  nest-dev-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecomerce_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres_data: